### ISSUE TITLE
ERROR [ExceptionHandler] Cannot destructure property 'source' of 'this._translationContextFactory(...)' as it is null.

### ISSUE THREAD

**Issue by Hussein-Kamareddine** [kyubisation/angular-t9n#10]
any idea about this issue? I am getting it after running "npm run t9n"

**Comment by Hussein-Kamareddine** [comment]
any update?

**Comment by kyubisation** [comment]
Hello @Hussein-Kamareddine 
Without a reproduction or any details I cannot easily interpret what could be the error.
How are you using angular-t9n and how does your angular.json look like?

**Comment by Hussein-Kamareddine** [comment]
Hi @kyubisation ,

here is the angular-t9n part in my angular.json

```
"t9n": {
          "builder": "angular-t9n:t9n",
          "options": {
            "translationFile": "src/i18n/messages.xlf",
            "targetTranslationPath": "src/locales",
            "includeContextInTarget": true
          }
        }
```
I am using angular 13.1.1

**Comment by kyubisation** [comment]
This should either be solved or the error message improved with v14.
