### ISSUE TITLE
UI doens't look good after updating to 15.0.1

### ISSUE THREAD

**Issue by nielsboogaard** [kyubisation/angular-t9n#34]
I've upgrade (besides my Angular application and Angular material to v15) angular-t9n to v15.0.1, but now the user interface doesn't look good. See screenshot:

<img width="436" alt="Screenshot 2023-01-11 at 09 03 24" src="https://user-images.githubusercontent.com/6429287/211750939-a2a3d321-69c0-4d8d-8443-1a8d0b5a8d34.png">

Might be caused by incompatible changes in the newest Material version used within the t9n UI?

**Comment by kyubisation** [comment]
Thanks for bringing this to my attention.
I'll try to have a look.

**Comment by nielsboogaard** [comment]
Any update on this @kyubisation ?

**Comment by kyubisation** [comment]
Unfortunately, no. I've been fairly busy with work. I'll try to free some time in march.

**Comment by ytsurk** [comment]
Same for the detail view:

![grafik](https://user-images.githubusercontent.com/455010/222733138-28fafc39-dd19-4977-8867-4e1643f6cc9b.png)

and overview (dropdown button):

![grafik](https://user-images.githubusercontent.com/455010/222733353-38ded363-f250-42c1-9dbe-dd38dfaa4935.png)

**Comment by kyubisation** [comment]
This should be fixed with 15.0.2

**Comment by ytsurk** [comment]
Looks great - Thankx!

**Comment by nielsboogaard** [comment]
Thanks 👍🏻
