### ISSUE TITLE
Failing with no message on nx workspace

### ISSUE THREAD

**Issue by DaSchTour** [kyubisation/angular-t9n#9]
I tried to run this inside an nx workspace, but sadly it fails without any error message. Even in debug mode it fails without any messages. Could you add a little bit of logging so it would be possible to debug errors.

**Comment by kyubisation** [comment]
Sure. Could you provide a minimal reproduction? I'm not directly familiar with nx workspaces.

**Comment by kyubisation** [comment]
Closing due to lack of reaction. Added additional log statements.
